/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HQSE_5;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
