/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HQSE_5;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        GetOpt d = new GetOpt(args);

        String[] test;

        test = d.getTheArgs();

        //System.out.println(test[0]);
        //System.out.println(new App().getGreeting());
    }
}
