/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HQSE_5;

import jdk.nashorn.internal.runtime.options.Options;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        //System.out.println(new App().getGreeting());
    }
}
